# Configuration file for GATK RNA-seq variant calling pipeline
#--------------
# Sample information
fastq_dir: "/projects/prjs1616/gatk_paper_demo/data/liver_fastq" 

# Reference files
reference:
  fasta: "/projects/prjs1616/gatk_paper_demo/resources/star_hg38_index/GRCh38.primary_assembly.genome.fa" 
  dbsnp: "/projects/prjs1616/gatk_paper_demo/resources/known_variants/Homo_sapiens_assembly38.dbsnp138.vcf" 
  mills_indels: "/projects/prjs1616/gatk_paper_demo/resources/known_variants/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  star_index_dir: "/projects/prjs1616/gatk_paper_demo/resources/star_hg38_index/star_hg38_index"
  #sample_map: "/projects/prjs1616/baria_gatk/data/BARIA_sample_map"

envs: "/projects/prjs1616/gatk_paper_demo/workflow/envs"

#-------------
# Chromosomes for parallel processing
chromosomes: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", 
              "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", 
              "chr20", "chr21", "chr22", "chrX", "chrY"]


#--------------
# Output directories
output_dir: "/projects/prjs1616/gatk_paper_demo/results"
log_dir: "/projects/prjs1616/gatk_paper_demo/logs"
temp_dir: "/projects/prjs1616/gatk_paper_demo/temp"



#--------------
resources:
  fastq_to_bam:
    threads: 64
    memory: 64  # in GB

  mark_duplicates: 
    threads: 64
    memory: 64  # in GB

  filter_contigs:
    threads: 24
    memory: 32  # in GB


  index_bam:
    threads: 24
    memory: 32  # in GB


  split_n_cigar_reads:
    threads: 96
    memory: 32  # in GB


  bqsr:
    threads: 24
    memory: 32  # in GB

  haplotype_caller:
    threads: 96
    memory: 32  # in GB

  GenomicsDB:
    threads: 96
    memory: 96  # in GB

  join_caller:
    threads: 96
    memory: 96  # in GB


# Filtering parameters
variant_filters:
  name: "RNASeqFilter"
  expression: "QD < 5.0 || FS > 20.0 || SOR > 3.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
  min_confidence: 20.0


